steps:
# Step 1: Install Python dependencies from your requirements.txt file.
- name: 'gcr.io/cloud-builders/pip'
  id: 'Install Dependencies'
  args: ['install', '-r', 'requirements.txt', '--user']

# Step 2: Run your Python script to deploy the agent to Agent Engine and capture the output.
- name: 'python:3.9'
  id: 'Deploy to AgentEngine'
  entrypoint: 'bash'
  args:
    - -c
    - |
      # Pass the project, location, and bucket as flags using Cloud Build substitutions
      python deploy.py --create \
        --project_id="$PROJECT_ID" \
        --location="$LOCATION" \
        --bucket="gcp-basic-371423-vertex-staging" \
      2>&1 | \
      grep 'Created remote agent:' | \
      awk '{print $4}' > /workspace/reasoning_engine_id.txt

# Step 3: Read the ID from the file and use it to register the agent in Agent Space.
- name: 'gcr.io/cloud-builders/gcurl'
  id: 'Register in AgentSpace'
  entrypoint: 'bash'
  args:
    - -c
    - |
      # Read the resource ID from the file into a shell variable.
      REASONING_ENGINE_ID=$(cat /workspace/reasoning_engine_id.txt)
      APP_ID="agentspace-de-agent-testin_1747856989394"

      # A safety check to ensure the ID was actually captured.
      if [ -z "$REASONING_ENGINE_ID" ]; then
        echo "ERROR: Reasoning Engine ID could not be found!"
        exit 1
      fi

      # Execute the curl command, substituting the shell variable into the JSON payload.
      curl -X POST \
      -H "Authorization: Bearer $(gcloud auth print-access-token)" \
      -H "Content-Type: application/json" \
      -H "X-Goog-User-Project: $PROJECT_ID" \
      -d '{
        "displayName": "Multi_tool_agent",
        "description": "Test deploying agent",
        "icon": {
          "uri": "https://www.gstatic.com/marketing-cms/assets/images/3d/24/88d3db994ac296ff541ca1b31674/google-health-studies.webp=s96-fcrop64=1,00000000ffffffff-rw"
        },
        "adk_agent_definition": {
          "tool_settings": {
            "tool_description": "Use this tool to get information on weather and time of a particular city"
          },
          "provisioned_reasoning_engine": {
            "reasoning_engine": "'$REASONING_ENGINE_ID'"
          }
        }
      }' \
      "https://discoveryengine.googleapis.com/v1alpha/projects/gcp-basic-371423/locations/global/collections/default_collection/engines/$APP_ID/assistants/default_assistant/agents"

# Optional: Set a timeout for the entire build process.
timeout: '1200s'